create table public.med_five_doctors (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name_en character varying null,
  name_ar character varying null,
  social_url text null,
  specialization_en text null,
  specialization_ar text null,
  image_asset text null,
  constraint med_five_doctors_pkey primary key (id)
) TABLESPACE pg_default;

create table public.med_five_booking_slot_reservations (
  id uuid not null default gen_random_uuid (),
  booking_id uuid not null,
  booking_date date not null,
  time_slot text not null,
  created_at timestamp with time zone null default now(),
  service_name text not null,
  doctor text null,
  constraint booking_slot_reservations_pkey primary key (id),
  constraint booking_slot_reservations_booking_id_fkey foreign KEY (booking_id) references bookings (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_booking_slot_reservations_booking_date on public.med_five_booking_slot_reservations using btree (booking_date) TABLESPACE pg_default;

create index IF not exists idx_med_five_booking_slot_reservations_booking_date on public.med_five_booking_slot_reservations using btree (booking_date) TABLESPACE pg_default;

create unique INDEX IF not exists med_five_booking_slot_doctor_unique on public.med_five_booking_slot_reservations using btree (
  booking_date,
  time_slot,
  service_name,
  COALESCE(doctor, ''::text)
) TABLESPACE pg_default;


create table public.med_five_spotlights (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  video text not null,
  title text not null default ''::text,
  description text not null,
  views bigint null default '0'::bigint,
  title_ar text not null,
  desc_ar text not null,
  constraint med_five_spotlights_pkey primary key (id)
) TABLESPACE pg_default;

create table public.med_five_contact_inquiries (
  id uuid not null default gen_random_uuid (),
  name text not null,
  email text not null,
  phone text not null,
  created_at timestamp with time zone null default now(),
  constraint med_five_contact_inquiries_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_med_five_contact_inquiries_created_at on public.med_five_contact_inquiries using btree (created_at desc) TABLESPACE pg_default;